### ISSUE TITLE
Add support for multiple DNS

### ISSUE THREAD

**Issue by neilpanchal** [usgraphics/TR-100#7]
![CleanShot 2024-06-10 at 20 45 01@2x](https://github.com/usgraphics/TR-100/assets/8161031/d7cb373b-d443-4b61-bdf2-6d98abfea50c)

Multiple DNS is pretty normal so we should prioritize this.

**Comment by kinduff** [comment]
Same but IPv6

```
│ MACHINE IP │                               │
│ CLIENT  IP │                               │
│ DNS     IP │ 192.168.1.254
2806:10c8:ffff::e
2806:1010:ffff:4::e │
│ USER       │ kinduff                       │
├────────────┼───────────────────────────────┤
```

**Comment by k-lar** [comment]
In my pull request I already implemented this! It needs testing but I think it should work fine for IPv4 and IPv6.
